Se creo la estructura de la interfaz del menu principal
FreddyA12/reservas-aulas-front pull request #26
Opened 2024-05-16 15:58 UTC by melanieAlban

revisar la interfaz

2024-05-16 16:05 UTC, rafaelsoriano04 requested changes

2024-05-16 16:05 UTC, rafaelsoriano04 commented on build.gradle
> +	implementation 'org.netbeans.external:AbsoluteLayout:RELEASE802'
Corregir la dependencia, dejar como están en develop por favor

2024-05-16 16:11 UTC, melanieAlban commented on build.gradle
> +	implementation 'org.netbeans.external:AbsoluteLayout:RELEASE802'
Se resolvió la solicitud de cambio revisar por favor

2024-05-16 16:15 UTC, rafaelsoriano04 approved these changes

2024-05-17 22:02 UTC, alisonMSalas approved these changes

2024-05-17 22:02 UTC, merged